name: build push and deploy image

on:
  push: 
     branches: [main]
  pull_request:
     branches: [main] 

permissions:
  id-token: write
  contents: read

env:
   AWS_REGION: us-east-1
   AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }} # to pull role-to-assume for github action 
   ECR_REPO_NAME: dev1
   IMAGE_TAG: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest # github runner
    steps: # Are for the build 
      - name: clone repo
        uses: actions/checkout@v5
      - name: AWS creds config #   need aws creds to login
        uses: aws-actions/configure-aws-credentials@v5
        with: # input for action
          role-to-assume: ${{ env.AWS_ROLE }}   #Open ID Connect OIDC: some of our pipline have access key and secret key from AWS, and right now I am refactioring those pipeline to us OIDC in state.  So we are useing a role in AWS instead of generating a key that we are plucking from GitHub action.
          aws-region: ${{ env.AWS_REGION }}
      - name: loging to ecr
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login # the meta data for the task gets store in this id.  it a like a big variable that have multi things in here:  repository, url, region that was used to login
      - name: Build and tag image
        id: build-and-push # alias to refer to later
        run: | # | is to run multiply command
            docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} . 
            
      
      # Scan before push
      - name: Scan docker Image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
      - name: Push image to ecr
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}



      
